name: Portal_Full_Embed CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/PortalAndEmbedTests.js'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      shell: cmd
    - run: npm run test1
      shell: cmd
